title: Mikhail Nasyrov
lang: en
url: https://mnasyrov.com
author: Mikhail Nasyrov
twitter:
  username: mnasyrov
  card: summary
social:
  name: Mikhail Nasyrov
  links:
    - https://www.linkedin.com/in/mnasyrov
    - https://github.com/mnasyrov
